name: concurrent_run_ana_api_matrix_kalanlar_ub

on:
  workflow_dispatch:

jobs:
  scrape:
    # runs-on: ubuntu-latest
    runs-on: ubicloud-standard-2

    env:
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      PG_CONNECTION_STRING_BASE: ${{ secrets.PG_CONNECTION_STRING_BASE }}
      PG_VIEW_NAME: ${{ secrets.PG_VIEW_NAME }}
      PG_SUPABASEURL: ${{ secrets.PG_SUPABASEURL }}
      PG_SUPABASEKEY: ${{ secrets.PG_SUPABASEKEY }}
      PG_PROXYPORT: ${{ secrets.PG_PROXYPORT }}
      PG_PROXYUSERNAME: ${{ secrets.PG_PROXYUSERNAME }}
      PG_PROXYPASSWORD: ${{ secrets.PG_PROXYPASSWORD }}
      PROXY_IP: ${{ secrets.PROXY_IP }}
      PROXY_PORT: ${{ secrets.PROXY_PORT }}
      PROXY_USER: ${{ secrets.PROXY_USER }}
      PROXY_PASS: ${{ secrets.PROXY_PASS }}
      PG_SCRPEANT: ${{ secrets.PG_SCRPEANT }} 
      NODE_OPTIONS: --unhandled-rejections=strict

    strategy:
      matrix:
        script: [
              "scrape_api_tum_concurrent_kalanlar.mjs"
        ]

    steps:
     
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Run scraper
        run: |
          echo "Running scraper: ${{ matrix.script }}"
          node ana_links/${{ matrix.script }}
